version: '3'
services:
  discord-music-bot:
    build:
      context: .
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN:?no DISCORD_BOT_TOKEN set}
    command: [ "debug" ]
    ports:
      - 5678:5678
    restart: always
